
const propsDropdown = {
    defaultValue: { value: 0, label: '' },
    options: [
        { value: '基隆市', label: '基隆市' },
        { value: '台北市', label: '台北市' },
        { value: '新北市', label: '新北市' },
        { value: '桃園市', label: '桃園市' },
        { value: '新竹市', label: '新竹市' },
        { value: '新竹縣', label: '新竹縣' },
        { value: '苗栗縣', label: '苗栗縣' },
        { value: '台中市', label: '台中市' },
        { value: '彰化縣', label: '彰化縣' },
        { value: '雲林縣', label: '雲林縣' },
        { value: '南投縣', label: '南投縣' },
        { value: '嘉義市', label: '嘉義市' },
        { value: '嘉義縣', label: '嘉義縣' },
        { value: '台南市', label: '台南市' },
        { value: '高雄市', label: '高雄市' },
        { value: '屏東縣', label: '屏東縣' },
        { value: '台東縣', label: '台東縣' },
        { value: '花蓮縣', label: '花蓮縣' },
        { value: '宜蘭縣', label: '宜蘭縣' },
        { value: '澎湖縣', label: '澎湖縣' },
        { value: '連江縣', label: '連江縣' },
        { value: '金門縣', label: '金門縣' },
    ],
    label: '您所在的城市',
    animationType: 'none',
  };
  
  //dropdown district 的資料表
  
  const dis = [
    {
        district: '台北市',
        dropdown: {
            defaultValue: { value: 0, label: '請選擇地區' },
  
            options: [
                { value: '中正', label: '中正' },
                { value: '大同', label: '大同' },
                { value: '中山', label: '中山' },
                { value: '松山', label: '松山' },
                { value: '大安', label: '大安' },
                { value: '萬華', label: '萬華' },
                { value: '信義', label: '信義' },
                { value: '士林', label: '士林' },
                { value: '北投', label: '北投' },
                { value: '內湖', label: '內湖' },
                { value: '南港', label: '南港' },
                { value: '文山', label: '文山' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '基隆市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '仁愛', label: '仁愛' },
                { value: '中正', label: '中正' },
                { value: '信義', label: '信義' },
                { value: '中山', label: '中山' },
                { value: '安樂', label: '安樂' },
                { value: '暖暖', label: '暖暖' },
                { value: '七堵', label: '七堵' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '新北市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '萬里', label: '萬里' },
                { value: '金山', label: '金山' },
                { value: '板橋', label: '板橋' },
                { value: '汐止', label: '汐止' },
                { value: '深坑', label: '深坑' },
                { value: '石碇', label: '石碇' },
                { value: '瑞芳', label: '瑞芳' },
                { value: '平溪', label: '平溪' },
                { value: '雙溪', label: '雙溪' },
                { value: '貢寮', label: '貢寮' },
                { value: '新店', label: '新店' },
                { value: '坪林', label: '坪林' },
                { value: '烏來', label: '烏來' },
                { value: '永和', label: '永和' },
                { value: '中和', label: '中和' },
                { value: '土城', label: '土城' },
                { value: '三峽', label: '三峽' },
                { value: '鶯歌', label: '鶯歌' },
                { value: '樹林', label: '樹林' },
                { value: '新莊', label: '新莊' },
                { value: '三重', label: '三重' },
                { value: '蘆洲', label: '蘆洲' },
                { value: '五股', label: '五股' },
                { value: '泰山', label: '泰山' },
                { value: '林口', label: '林口' },
                { value: '八里', label: '八里' },
                { value: '淡水', label: '淡水' },
                { value: '三芝', label: '三芝' },
                { value: '石門', label: '石門' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '桃園市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '桃園', label: '桃園' },
                { value: '中壢', label: '中壢' },
                { value: '平鎮', label: '平鎮' },
                { value: '八德', label: '八德' },
                { value: '楊梅', label: '楊梅' },
                { value: '蘆竹', label: '蘆竹' },
                { value: '大溪', label: '大溪' },
                { value: '龍潭', label: '龍潭' },
                { value: '龜山', label: '龜山' },
                { value: '大園', label: '大園' },
                { value: '觀音', label: '觀音' },
                { value: '新屋', label: '新屋' },
                { value: '復興', label: '復興' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '新竹市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '東區', label: '東區' },
                { value: '北區', label: '北區' },
                { value: '香山', label: '香山' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '新竹縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '竹北', label: '竹北' },
                { value: '竹東', label: '竹東' },
                { value: '新埔', label: '新埔' },
                { value: '關西', label: '關西' },
                { value: '湖口', label: '湖口' },
                { value: '新豐', label: '新豐' },
                { value: '峨眉', label: '峨眉' },
                { value: '寶山', label: '寶山' },
                { value: '北埔', label: '北埔' },
                { value: '芎林', label: '芎林' },
                { value: '橫山', label: '橫山' },
                { value: '尖石', label: '尖石' },
                { value: '五峰', label: '五峰' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '苗栗縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '苗栗', label: '苗栗' },
                { value: '頭份', label: '頭份' },
                { value: '竹南', label: '竹南' },
                { value: '後龍', label: '後龍' },
                { value: '通霄', label: '通霄' },
                { value: '苑裡', label: '苑裡' },
                { value: '卓蘭', label: '卓蘭' },
                { value: '造橋', label: '造橋' },
                { value: '西湖', label: '西湖' },
                { value: '頭屋', label: '頭屋' },
                { value: '公館', label: '公館' },
                { value: '銅鑼', label: '銅鑼' },
                { value: '三義', label: '三義' },
                { value: '大湖', label: '大湖' },
                { value: '獅潭', label: '獅潭' },
                { value: '三灣', label: '三灣' },
                { value: '南庄', label: '南庄' },
                { value: '泰安', label: '泰安' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '台中市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '中區', label: '中區' },
                { value: '東區', label: '東區' },
                { value: '南區', label: '南區' },
                { value: '西區', label: '西區' },
                { value: '北區', label: '北區' },
                { value: '北屯', label: '北屯' },
                { value: '西屯', label: '西屯' },
                { value: '南屯', label: '南屯' },
                { value: '太平', label: '太平' },
                { value: '大里', label: '大里' },
                { value: '霧峰', label: '霧峰' },
                { value: '烏日', label: '烏日' },
                { value: '豐原', label: '豐原' },
                { value: '后里', label: '后里' },
                { value: '石岡', label: '石岡' },
                { value: '東勢', label: '東勢' },
                { value: '新社', label: '新社' },
                { value: '潭子', label: '潭子' },
                { value: '大雅', label: '大雅' },
                { value: '神岡', label: '神岡' },
                { value: '大肚', label: '大肚' },
                { value: '沙鹿', label: '沙鹿' },
                { value: '龍井', label: '龍井' },
                { value: '梧棲', label: '梧棲' },
                { value: '清水', label: '清水' },
                { value: '大甲', label: '大甲' },
                { value: '外埔', label: '外埔' },
                { value: '大安', label: '大安' },
                { value: '和平', label: '和平' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '彰化縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '彰化', label: '彰化' },
                { value: '員林', label: '員林' },
                { value: '和美', label: '和美' },
                { value: '鹿港', label: '鹿港' },
                { value: '溪湖', label: '溪湖' },
                { value: '二林', label: '二林' },
                { value: '田中', label: '田中' },
                { value: '北斗', label: '北斗' },
                { value: '花壇', label: '花壇' },
                { value: '芬園', label: '芬園' },
                { value: '大村', label: '大村' },
                { value: '永靖', label: '永靖' },
                { value: '伸港', label: '伸港' },
                { value: '線西', label: '線西' },
                { value: '福興', label: '福興' },
                { value: '秀水', label: '秀水' },
                { value: '埔心', label: '埔心' },
                { value: '埔鹽', label: '埔鹽' },
                { value: '大城', label: '大城' },
                { value: '芳苑', label: '芳苑' },
                { value: '竹塘', label: '竹塘' },
                { value: '社頭', label: '社頭' },
                { value: '二水', label: '二水' },
                { value: '田尾', label: '田尾' },
                { value: '埤頭', label: '埤頭' },
                { value: '溪州', label: '溪州' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '南投縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '南投', label: '南投' },
                { value: '埔里', label: '埔里' },
                { value: '草屯', label: '草屯' },
                { value: '竹山', label: '竹山' },
                { value: '集集', label: '集集' },
                { value: '名間', label: '名間' },
                { value: '鹿谷', label: '鹿谷' },
                { value: '中寮', label: '中寮' },
                { value: '魚池', label: '魚池' },
                { value: '國姓', label: '國姓' },
                { value: '水里', label: '水里' },
                { value: '信義', label: '信義' },
                { value: '仁愛', label: '仁愛' },
               
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '雲林縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '斗六', label: '斗六' },
                { value: '斗南', label: '斗南' },
                { value: '虎尾', label: '虎尾' },
                { value: '西螺', label: '西螺' },
                { value: '土庫', label: '土庫' },
                { value: '北港', label: '北港' },
                { value: '林內', label: '林內' },
                { value: '古坑', label: '古坑' },
                { value: '大埤', label: '大埤' },
                { value: '莿桐', label: '莿桐' },
                { value: '褒忠', label: '褒忠' },
                { value: '二崙', label: '二崙' },
                { value: '崙背', label: '崙背' },
                { value: '麥寮', label: '麥寮' },
                { value: '臺西', label: '臺西' },
                { value: '東勢', label: '東勢' },
                { value: '元長', label: '元長' },
                { value: '四湖', label: '四湖' },
                { value: '口湖', label: '口湖' },
                { value: '水林', label: '水林' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '嘉義市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '東區', label: '東區' },
                { value: '西區', label: '西區' },
               
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '嘉義縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '太保', label: '太保' },
                { value: '朴子', label: '朴子' },
                { value: '布袋', label: '布袋' },
                { value: '大林', label: '大林' },
                { value: '民雄', label: '民雄' },
                { value: '溪口', label: '溪口' },
                { value: '新港', label: '新港' },
                { value: '六腳', label: '六腳' },
                { value: '東石', label: '東石' },
                { value: '義竹', label: '義竹' },
                { value: '鹿草', label: '鹿草' },
                { value: '水上', label: '水上' },
                { value: '中埔', label: '中埔' },
                { value: '竹崎', label: '竹崎' },
                { value: '梅山', label: '梅山' },
                { value: '番路', label: '番路' },
                { value: '大埔', label: '大埔' },
                { value: '阿里山', label: '阿里山' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '台南市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '中西', label: '中西' },
                { value: '東區', label: '東區' },
                { value: '南區', label: '南區' },
                { value: '北區', label: '北區' },
                { value: '安平', label: '安平' },
                { value: '安南', label: '安南' },
                { value: '永康', label: '永康' },
                { value: '歸仁', label: '歸仁' },
                { value: '新化', label: '新化' },
                { value: '左鎮', label: '左鎮' },
                { value: '玉井', label: '玉井' },
                { value: '楠西', label: '楠西' },
                { value: '南化', label: '南化' },
                { value: '仁德', label: '仁德' },
                { value: '關廟', label: '關廟' },
                { value: '龍崎', label: '龍崎' },
                { value: '官田', label: '官田' },
                { value: '麻豆', label: '麻豆' },
                { value: '佳里', label: '佳里' },
                { value: '西港', label: '西港' },
                { value: '七股', label: '七股' },
                { value: '將軍', label: '將軍' },
                { value: '學甲', label: '學甲' },
                { value: '北門', label: '北門' },
                { value: '新營', label: '新營' },
                { value: '後壁', label: '後壁' },
                { value: '白河', label: '白河' },
                { value: '東山', label: '東山' },
                { value: '六甲', label: '六甲' },
                { value: '下營', label: '下營' },
                { value: '柳營', label: '柳營' },
                { value: '鹽水', label: '鹽水' },
                { value: '善化', label: '善化' },
                { value: '大內', label: '大內' },
                { value: '山上', label: '山上' },
                { value: '新市', label: '新市' },
                { value: '安定', label: '安定' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '高雄市',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '楠梓', label: '楠梓' },
                { value: '左營', label: '左營' },
                { value: '鼓山', label: '鼓山' },
                { value: '三民', label: '三民' },
                { value: '鹽埕', label: '鹽埕' },
                { value: '前金', label: '前金' },
                { value: '新興', label: '新興' },
                { value: '苓雅', label: '苓雅' },
                { value: '前鎮', label: '前鎮' },
                { value: '旗津', label: '旗津' },
                { value: '小港', label: '小港' },
                { value: '鳳山', label: '鳳山' },
                { value: '大寮', label: '大寮' },
                { value: '鳥松', label: '鳥松' },
                { value: '林園', label: '林園' },
                { value: '仁武', label: '仁武' },
                { value: '大樹', label: '大樹' },
                { value: '大社', label: '大社' },
                { value: '岡山', label: '岡山' },
                { value: '路竹', label: '路竹' },
                { value: '橋頭', label: '橋頭' },
                { value: '梓官', label: '梓官' },
                { value: '彌陀', label: '彌陀' },
                { value: '永安', label: '永安' },
                { value: '燕巢', label: '燕巢' },
                { value: '田寮', label: '田寮' },
                { value: '阿蓮', label: '阿蓮' },
                { value: '茄萣', label: '茄萣' },
                { value: '湖內', label: '湖內' },
                { value: '旗山', label: '旗山' },
                { value: '美濃', label: '美濃' },
                { value: '內門', label: '內門' },
                { value: '杉林', label: '杉林' },
                { value: '甲仙', label: '甲仙' },
                { value: '六龜', label: '六龜' },
                { value: '茂林', label: '茂林' },
                { value: '桃源', label: '桃源' },
                { value: '那瑪夏', label: '那瑪夏' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '屏東縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '屏東', label: '屏東' },
                { value: '潮州', label: '潮州' },
                { value: '東港', label: '東港' },
                { value: '恆春', label: '恆春' },
                { value: '萬丹', label: '萬丹' },
                { value: '長治', label: '長治' },
                { value: '麟洛', label: '麟洛' },
                { value: '九如', label: '九如' },
                { value: '里港', label: '里港' },
                { value: '鹽埔', label: '鹽埔' },
                { value: '高樹', label: '高樹' },
                { value: '萬巒', label: '萬巒' },
                { value: '內埔', label: '內埔' },
                { value: '竹田', label: '竹田' },
                { value: '新埤', label: '新埤' },
                { value: '枋寮', label: '枋寮' },
                { value: '新園', label: '新園' },
                { value: '崁頂', label: '崁頂' },
                { value: '林邊', label: '林邊' },
                { value: '南州', label: '南州' },
                { value: '佳冬', label: '佳冬' },
                { value: '琉球', label: '琉球' },
                { value: '車城', label: '車城' },
                { value: '滿州', label: '滿州' },
                { value: '枋山', label: '枋山' },
                { value: '霧臺', label: '霧臺' },
                { value: '瑪家', label: '瑪家' },
                { value: '泰武', label: '泰武' },
                { value: '來義', label: '來義' },
                { value: '春日', label: '春日' },
                { value: '獅子', label: '獅子' },
                { value: '牡丹', label: '牡丹' },
                { value: '三地門', label: '三地門' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '台東縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '臺東', label: '臺東' },
                { value: '成功', label: '成功' },
                { value: '關山', label: '關山' },
                { value: '長濱', label: '長濱' },
                { value: '池上', label: '池上' },
                { value: '東河', label: '東河' },
                { value: '鹿野', label: '鹿野' },
                { value: '卑南', label: '卑南' },
                { value: '大武', label: '大武' },
                { value: '綠島', label: '綠島' },
                { value: '太麻里', label: '太麻里' },
                { value: '海端', label: '海端' },
                { value: '延平', label: '延平' },
                { value: '金峰', label: '金峰' },
                { value: '達仁', label: '達仁' },
                { value: '蘭嶼', label: '蘭嶼' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '花蓮縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '花蓮', label: '花蓮' },
                { value: '鳳林', label: '鳳林' },
                { value: '玉里', label: '玉里' },
                { value: '新城', label: '新城' },
                { value: '吉安', label: '吉安' },
                { value: '壽豐', label: '壽豐' },
                { value: '光復', label: '光復' },
                { value: '豐濱', label: '豐濱' },
                { value: '瑞穗', label: '瑞穗' },
                { value: '富里', label: '富里' },
                { value: '秀林', label: '秀林' },
                { value: '萬榮', label: '萬榮' },
                { value: '卓溪', label: '卓溪' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '宜蘭縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '宜蘭', label: '宜蘭' },
                { value: '頭城', label: '頭城' },
                { value: '羅東', label: '羅東' },
                { value: '蘇澳', label: '蘇澳' },
                { value: '礁溪', label: '礁溪' },
                { value: '壯圍', label: '壯圍' },
                { value: '員山', label: '員山' },
                { value: '冬山', label: '冬山' },
                { value: '五結', label: '五結' },
                { value: '三星', label: '三星' },
                { value: '大同', label: '大同' },
                { value: '南澳', label: '南澳' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '澎湖縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '馬公', label: '馬公' },
                { value: '湖西', label: '湖西' },
                { value: '白沙', label: '白沙' },
                { value: '西嶼', label: '西嶼' },
                { value: '望安', label: '望安' },
                { value: '七美', label: '七美' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '金門縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '金城', label: '金城' },
                { value: '金湖', label: '金湖' },
                { value: '金沙', label: '金沙' },
                { value: '金寧', label: '金寧' },
                { value: '烈嶼', label: '烈嶼' },
                { value: '烏坵', label: '烏坵' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
    {
        district: '連江縣',
        dropdown: {
            defaultValue: { value: 1, label: '請選擇地區' },
            options: [
                { value: '南竿', label: '南竿' },
                { value: '北竿', label: '北竿' },
                { value: '莒光', label: '莒光' },
                { value: '東引', label: '東引' },
            ],
            label: '您所在的區域',
            animationType: 'none',
        }
    },
  ]
  
  
  
  export const city = propsDropdown;
  export const  district = dis;